apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myakscluster-14bd"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myakscluster-14bd"
  template:
    metadata:
      labels:
        app: "myakscluster-14bd"
    spec:
      containers:
        - name: "myakscluster-14bd"
          image: "myregistryii.azurecr.io/myakscluster"
          ports:
          - containerPort: 8080